name: Publish OpenFactory devcontainer image

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: ghcr.io/openfactoryio/devcontainer-py3.12
            base: python:3.12-slim-bullseye
          - name: ghcr.io/openfactoryio/devcontainer-py3.13
            base: python:3.13-slim-bookworm
          - name: ghcr.io/openfactoryio/devcontainer-py3.14
            base: python:3.14-slim-bookworm

    steps:

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Validate release tag version
        if: github.event_name == 'release' && github.event.action == 'created'
        run: ./scripts/validate_version.sh ${{ github.ref_name }}

      - name: Set tags dynamically
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAGS=${{ matrix.image.name }}:manual-${{ github.sha }}" >> $GITHUB_ENV
            echo "TAGS_LATEST=${{ matrix.image.name }}:latest" >> $GITHUB_ENV
            echo "VERSION=dev" >> $GITHUB_ENV
            echo "OPENFACTORY_VERSION=main" >> $GITHUB_ENV
          else
            echo "TAGS=${{ matrix.image.name }}:${{ github.ref_name }}" >> $GITHUB_ENV
            echo "TAGS_LATEST=${{ matrix.image.name }}:latest" >> $GITHUB_ENV
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "OPENFACTORY_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./.devcontainer
          file: ./.devcontainer/Dockerfile
          push: true
          build-args: |
            PYTHON_BASE_IMAGE=${{ matrix.image.base }}
          tags: |
            ${{ env.TAGS }}
            ${{ env.TAGS_LATEST }}
